<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15555" started-at="2018-08-20T22:01:14Z" finished-at="2018-08-20T22:01:30Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="15555" started-at="2018-08-20T22:01:14Z" finished-at="2018-08-20T22:01:30Z">
      <class name="com.mockaroo.MockarooDataValidation">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.mockaroo.MockarooDataValidation@7d9d1a19]" name="setUp" is-config="true" duration-ms="6082" started-at="2018-08-20T22:01:14Z" finished-at="2018-08-20T22:01:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="DataValidation()[pri:0, instance:com.mockaroo.MockarooDataValidation@7d9d1a19]" name="DataValidation" duration-ms="9437" started-at="2018-08-20T22:01:20Z" finished-at="2018-08-20T22:01:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [city,country] but found [id,first_name,last_name,email,gender]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [city,country] but found [id,first_name,last_name,email,gender]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.mockaroo.MockarooDataValidation.DataValidation(MockarooDataValidation.java:158)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DataValidation -->
      </class> <!-- com.mockaroo.MockarooDataValidation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
